version: 2.1

general:
# Uncomment the following to specify only a specific branch
#   branches:
#     only:
#       - dev # specific branch
#       - /dev-.*/ # or regexes

jobs:
  build:
    machine: true
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
      - SFDX_DISABLE_ENCRYPTION: true
    steps:
      - checkout
      - run:
          name: "Create SFDX Folder" 
          command: |
            # Create sfdx directory
            mkdir ~/sfdx
      - run:
          name: Download CLI
          command: |
            # Download cli
            # By default, the script installs the current version of Salesforce CLI. To install the release candidate, set the DX_CLI_URL_CUSTOM local variable to the appropriate URL
            wget -qO- ${DX_CLI_URL_CUSTOM-$DX_CLI_URL} | tar xJ -C ~/sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            # Install the cli
            export PATH=~/sfdx/bin:$PATH
            echo "export PATH=~/sfdx/bin:$PATH" >> $BASH_ENV
            sfdx
            echo 'make hub key'
            echo $HUB_SERVER_KEY_HEX | xxd -r -ps >> keys/hub.key
            openssl rsa -in keys/hub.key -check -noout
            sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile keys/hub.key --username $HUB_SFDC_USER --setdefaultdevhubusername -a hub
       - run:
          name: Deploy to Target Deployment Org
          command: |
            #Deploy to target deployment org and run unit tests. 
            sfdx force --help
            sfdx force:org:create -s -f config/project-scratch-def.json -a circle_build_$CIRCLE_BUILD_NUM
            sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM
            mkdir -p $CIRCLE_TEST_REPORTS/junit
            sfdx force:apex:test:run -c -d $CIRCLE_TEST_REPORTS/junit -r junit
            
            #Example shows how to run a check only deploy.
            #sfdx force:mdapi:deploy --checkonly --wait 10 --deploydir $DEPLOYDIR --targetusername UAT --testlevel $TESTLEVEL
        - run:
          name: Delete Useless Scratch Org
          command: |
            sfdx force:org:delete -u circle_build_$CIRCLE_BUILD_NUM -p
